name: windows_build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python.3.6.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install Cython numpy wheel setuptools
          pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Build Cython
        run: |
          pip install -e .
      - name: Unit tests
        run: |
          pip install pytest gym flask msgpack onnxruntime
          pip install git+https://github.com/takuseno/d4rl-atari
          mkdir -p test_data
          pytest tests -p no:warnings -v
      - name: Build distribution package
        run: |
          python setup.py test
          python setup.py sdist bdist_wheel
